services:
  postgis:
    image: postgis/postgis
    container_name: survey_postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      # - POSTGRES_DB=geodb
    volumes:
      - ./postgis/:/docker-entrypoint-initdb.d
    ports:
      - 5434:5432

  nodejs:
    image: node
    container_name: survey_nodejs
    working_dir: /app/nodejs
    restart: always
    depends_on:
      - postgis
    environment:
      - NODE_ENV=production
    volumes:
      - ./nodejs:/app/nodejs
    ports:
      - 3100:3000
    command: bash -c "npm i && npm i -g nodemon  && nodemon server.js"
